version: '3.8'

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready
      timeout: 5s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  migrate:
    build: .
    entrypoint: ["bun", "schema:migrate"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    ports:
      - "3000:3000"
  test:
    build: .
    entrypoint: ["bun", "test"]
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase



volumes:
  db_data:
