name: Format
jobs:
  my-job:
    name: format
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun format:check